[project]
name = "libero"
version = "0.1.0"
description = "LIBERO: Benchmarking Knowledge Transfer for Lifelong Robot Learning"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = "==3.10.*"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Bo Liu", email = "bliu@cs.utexas.edu" },
    { name = "Yifeng Zhu", email = "yifengz@cs.utexas.edu" },
    { name = "Chongkai Gao" },
    { name = "Yihao Feng" },
    { name = "Qiang Liu" },
    { name = "Yuke Zhu" },
    { name = "Peter Stone" },
]
dependencies = [
    "bddl==1.0.1",
    "cloudpickle==2.1.0",
    "easydict==1.9",
    "einops==0.4.1",
    "future==0.18.2",
    "gym==0.25.2",
    "hydra-core==1.2.0",
    "matplotlib==3.5.3",
    "numpy==1.22.4",
    "opencv-python==4.6.0.66",
    "robomimic==0.2.0",
    "robosuite==1.4.0",
    "thop==0.1.1.post2209072238",
    "torch==1.11.0+cu113",
    "torchaudio==0.11.0+cu113",
    "torchvision==0.12.0+cu113",
    "transformers==4.21.1",
    "wandb==0.13.1",
]

[project.urls]
Homepage = "https://libero-project.github.io"
Documentation = "https://lifelong-robot-learning.github.io/LIBERO/"
Repository = "https://github.com/Lifelong-Robot-Learning/LIBERO"
Paper = "https://arxiv.org/pdf/2306.03310.pdf"

[project.scripts]
"lifelong.main" = "libero.lifelong.main:main"
"lifelong.eval" = "libero.lifelong.evaluate:main"
"libero.config_copy" = "scripts.config_copy:main"
"libero.create_template" = "scripts.create_template:main"

[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["libero*", "scripts*", "templates*"]

[tool.setuptools.package-data]
libero = [
    "configs/**/*.yaml",
    "libero/assets/**/*",
    "libero/bddl_files/**/*.bddl",
    "libero/init_files/**/*",
]
templates = ["*.py", "*.xml"]

[tool.uv]
package = true
environments = [
  "sys_platform == 'linux' and platform_machine == 'x86_64'",
]

[tool.uv.sources]
torch = { index = "pytorch-cu113" }
torchvision = { index = "pytorch-cu113" }
torchaudio = { index = "pytorch-cu113" }

[[tool.uv.index]]
name = "pytorch-cu113"
url = "https://download.pytorch.org/whl/cu113"
explicit = true
